### ISSUE TITLE
Core: Debugger

### ISSUE THREAD

**Issue by minefled** [io-home-app/core#2]
The Debugger will be used during development and potentially to discover bugs in production later. It consists of a Debugger class that will receive the events and manage everything, a WebSocket API and a Web-Based debugger to simplify the debugging proccess

*This might be edited / expanded in the future*

## To-Do

- [ ] Debugger Class To receive the Events
- [ ] Web Server
    - [ ] Express server with static files for dashboard
    - [ ] Websocket API
        - [ ] Client Manager
 - [ ] Web Dashboard
     - [ ] Event Bus Inspector
         - [ ] Event List
         - [ ] Event Distribution (How many of each event type has been fired; Donut Chart)
         - [ ] Event Source Activity (How many events each Event Source is publishing per minute)
     - [ ] Database Inspector
     - [ ] Integration Inspector
         - [ ] State Inspector
         - [ ] Service Inspector
