### ISSUE TITLE
Core: Database

### ISSUE THREAD

**Issue by minefled** [io-home-app/core#3]
The Database stores all data related to the Integrations, e.g. the history of the temperature of a sensor.

*This might be edited in the future*

## Todo

- [ ] Create Database Connection Class
    - [ ] Create mariadb connection
    - [ ] Create Tables dynamically
    - [ ] Querying functions
        - [ ] ...
